# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false

branches:
  only: master

before_install:
  - export PYTHON=""
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gcc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran -y ; fi

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("NNLS"); Pkg.test("NNLS"; coverage=true)'
 - julia -e 'Pkg.test("NNLS")'

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("NNLS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
