# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false

before_install:
  - export PYTHON=""
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gfortran            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran -y ; fi

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("NNLS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
