# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false

before_install:
  - export PYTHON=""

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("NNLS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
